name: Linting and Build test (dev)

on:
  pull_request:
    branches:
      - dev

jobs:
  lint_build:
    name: Lint code and build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: 20 # Matches the Node.js version that caused the error
          cache: 'pnpm'

      - name: Disable corepack strict verification (Temporary)
        run: echo 'COREPACK_ENABLE_STRICT=false' >> $GITHUB_ENV

      - name: Install pnpm@8.15.4
        run: |
          corepack enable
          corepack prepare pnpm@8.15.4 --activate
          pnpm clear-cache

      - name: Install dependencies
        run: pnpm install

      - name: Run linting and testing
        run: |
          pnpm lint
          pnpm build
